
# elk/tasks/elastic_plugins.yml

# to update plugins they must be uninstalled and re-installed
 - name: Uninstall plugins 
   command: >
            "{{ES_HOME}}/bin/plugin" -remove "{{item.plugin}}"
   with_items: elastic_plugins

 - name: Install plugins 
   command: creates="{{ES_PLUGINS_DIR}}/{{item.creates}}"
            "{{ES_HOME}}/bin/plugin" -install "{{item.plugin}}"
   with_items: elastic_plugins

 - name: Set ownership on plugins
   shell: chown -R "{{ES_USER}}:{{ES_USER}}" "{{ES_HOME}}/plugins"

 - name: Install marvel plugin
   command: creates="{{ES_HOME}}/plugins/marvel"
            "{{ES_HOME}}/bin/plugin" -install elasticsearch/marvel/latest
   when: install_marvel == "yes"